name: walletconnect_flutter_dapp
description: A dApp showing how to use WalletConnect v2 with Flutter

publish_to: "none"

version: 3.3.3

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  fl_toast: ^3.2.0
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  web3modal_flutter:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  json_serializable: ^6.8.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true

  assets:
    - assets/abis/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/AppIcon.png"
